sudo: false
language: ruby
cache: bundler
rvm:
- 2.4.2

install:
  # Install Jekyll and dependencies
  - bundle install

script: bundle exec rake site:deploy --quiet #--trace

# Generate your secure token with the travis gem:
# get Github token from your Travis CI profile page
# gem install travis
# GH_TOKEN from https://github.com/settings/tokens
# travis encrypt 'GIT_NAME="YOUR_USERNAME" GIT_EMAIL="YOUR_EMAIL" GH_TOKEN=YOUR_TOKEN'
env:
  global:
    secure: "kHFTvfzZhcJp74Pn0Ck5PR268kPgDJ7Au1Ivm+1n/18atDgs9T6u4C7MJr8sG5P1jXYSkdGaAJeHOWtE0NNCRraIAUggPTnoMPA6wxk4QcvVFcpV7HhTL1BwCK6REuCKZbb5VZrhu6QPzPd3/fQZJisoCJa3WwxxbLdjYmDgVHfAO8E3o+U2uaa1MyJmFH6CdFKrFQ9bWJvR/y5zxzCy7BOBGvTFDtLoK2e/quWDdII+DW1JJWyvlcAUFRrIp25lRaE6NlEt36ZPOO6m5V1XjH9fx3FyB1pzwOtOuaAHdz7BP5tXEwGFqDxsmOSMH1dKiG89aLQ0qLNE7fwHH0punRD9DciRGUsZ2XJOU1x/F9RKYKY0DbuB9Jhf0SvKvD1Mhq7psMjjPx+xeo1QnOIkUnZuYWZre4rQSTijBdp2vCGW8JR/6QtCsB2o05sCoPVLK/qybxEsIAEtT6UJOIAjb+kwASptJyrYDytQc8Rzvkv2x0mdIqc8tiaGtaSgr+3fCisCgV7jhTLIJeJRLs+k4Yd5QggpNIR+XC/mcEkWeTY8Daq29wRq1+1LwJy0qAZs6BwkOqkoMO3KeSNp/cJRHFcquBF9Xl6R7doNcowfb2VskAtNuvE7TTstm1GVvZPEKZATz/zocOwZENMwWK4Mqj1+NC/x716bNMLLSJ6WZ5s="
branches:
  only:
    - master
